baseURL = "https://docs.lenalab.org/"
title = "LENA"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Multilingual configuration
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ko]
    languageName = "한국어"
    weight = 1
    title = "LENA Docs"
    contentDir = "content/ko"
    
  [languages.en]
    languageName = "English"
    weight = 2
    title = "LENA Docs"
    contentDir = "content/en"

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "logo_lena_w_s.png"
